### ISSUE TITLE
Spessmen legs and feet are inverted

### ISSUE THREAD

**Issue by Alekshhh** [space-wizards/space-station-14#13754]
## Description
While making new sprites for the human and lizard races, I noticed something odd with the legs. Apparently, after some testing, I found out that:
- when facing left, the right foot goes over the left foot
- when facing right, the left leg goes over the right leg
This has been tested on the human race with custom colors, and observed on the lizard race with the same bug

**Reproduction**
- Be a spessman
- Question why god has made you this way

**Screenshots**

For context, red is left, green is right, blue is left, orange is right

![image2](https://user-images.githubusercontent.com/44923899/215167586-61a56ac9-3503-4957-9548-3484a42da733.png) facing right
![image](https://user-images.githubusercontent.com/44923899/215167589-88fc95a4-230b-43fc-849b-718b1b0b6aff.png) facing left

**Additional context**

How long has it been like this

**Comment by ElectroJr** [comment]
Its been like this for quite a long time and is just due to sprite layers not supporting some kind of direction dependent draw order.
I tried a shitty implementation for that some time ago, but I just stopped working on it and IMO the server-side sprite removal & sprite ECSing should be done first.

See space-wizards/space-station-14/pull/6984 & the other issues that it links to. This is also related to the buckle rotation draw order issues.

**Comment by lzk228** [comment]
i think it is fixed

**Comment by kosticia** [comment]
is that still valid?

**Comment by K-Dynamic** [comment]
I think it's still an issue given I just opened this one #39047, which focuses specifically on the legs
