### ISSUE TITLE
Can't spill the contents of Mop buckets & janicarts

### ISSUE THREAD

**Issue by DummeHytteOst** [space-wizards/space-station-14#15276]
When you open the verb menu for either the mop bucket or janicart then there is no spill contents option anymore, making it impossible to empty them

https://user-images.githubusercontent.com/94384139/230911561-23bbcf01-0b19-41f4-8501-0e8c41bbbb97.mp4

**Comment by Endecc** [comment]
I believe this is intentional as you're now _supposed_ to click and drag over the drain to empty the cart directly, as opposed to spilling it.

However I think some valid feedback is that the drain gets full incredibly quickly and/or doesn't delete enough internal fluids fast enough after a few rounds on Janitor testing it out, so having the alternative of spilling it again would be nice.

In short, I'm all for that option coming back.

**Comment by deltanedas** [comment]
shitter mimes spilling janicart is *very* annoying

**Comment by DummeHytteOst** [comment]
> I believe this is intentional as you're now _supposed_ to click and drag over the drain to empty the cart directly, as opposed to spilling it.
> 
> However I think some valid feedback is that the drain gets full incredibly quickly and/or doesn't delete enough internal fluids fast enough after a few rounds on Janitor testing it out, so having the alternative of spilling it again would be nice.
> 
> In short, I'm all for that option coming back.

ooh that makes sense, there was no indication for this since the change was not shown in the change log.
but still being able to spill the contents should be an option as you might need to, or want to spill the contents

**Comment by DummeHytteOst** [comment]
> shitter mimes spilling janicart is _very_ annoying

get security to arrest the mime for endangerment and possibly battery if it comes to that, janitors often have dangerous chemicals in their buckets that will harm people if they slip in it

**Comment by DawBla** [comment]
[#15300] should fix this

**Comment by deltanedas** [comment]
nope this still happens
![16:02:20](https://user-images.githubusercontent.com/39013340/233847417-0b795d73-0293-48d1-853a-be69ef303b65.png)

**Comment by Pangogie** [comment]
Fixed at some point.
