### ISSUE TITLE
Round start failures

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/space-station-14#16278]
Not sure if it's map or gamemode related but got reports of this since publish and now I am a mimir.

**Comment by deltanedas** [comment]
i think it happens when a gamemode vote ends (doesnt matter if it succeeds or fails from time remaining before starting it happened both times)
on lizard

**Comment by Slava0135** [comment]
fixed?

**Comment by Errant-4** [comment]
Nothing indicates that this is still a problem. Reopen if it can be reproduced
