### ISSUE TITLE
projectiles collide with open crates and lockers

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#17264]
## Description
probably shouldnt happen for crates at all since they are probably short enough
either way you shouldnt be able to shoot an open container you are standing in it makes no sense

**Comment by perryprog** [comment]
Fixed by #28072.

**Comment by Princess-Cheeseballs** [comment]
Hold your horses perry, this still happens with open lockers.

**Comment by perryprog** [comment]
... wauht? I tested it just now with PKA through open closet.

Edit: I'm going crazy; must've only tested crate.

**Comment by kontakt** [comment]
Should an open locker be bullet passable? Being able to toggle cover like that could be very strong.

**Comment by Princess-Cheeseballs** [comment]
> Should an open locker be bullet passable? Being able to toggle cover like that could be very strong.

currently people can walk through open lockers and use them as makeshift shields. Their health has been cut by about 100-50 points recently though so it's slightly less of an issue but still an issue.
