### ISSUE TITLE
Lights visibly update at the edge of the screen when power goes out

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/space-station-14#2379]
This bug is most visible when power goes out, but it's also visible when the lights turn back on.

**Comment by metalgearsloth** [comment]
This is from PVS. Probably needs a separate component for stuff that needs a higher update range (lights, potentially bullets).

**Comment by SweptWasTaken** [comment]
To replicate delete APC anywhere and check lights.

https://user-images.githubusercontent.com/49448379/126043770-8581478a-1bef-401f-bfb0-372f302dbb1a.mp4

**Comment by AJCM-git** [comment]
pretty sure this was fixed by paulvs

**Comment by ElectroJr** [comment]
It is still present, and quite noticeable with high latency where a player out-runs PVS, but definitely better than before. AFAIK there isn't really an easy fix for this, other than maybe making PVS somehow treat occluder & light entities separately.

But either way this issue should have been in engine, not content.
