### ISSUE TITLE
corpses cant be fire extinguished

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/space-station-14#24025]
## Description
only way to save them is attacking with water cups

**Comment by Arendian** [comment]
It's caused by an entities ability to collide with anything being disabled the moment they die.

**Comment by themias** [comment]
Fixed by #30532

**Comment by ThatGuyUSA** [comment]
Regular ol' Urist is fine, but unidentified corpses still have this problem for some reason

https://github.com/user-attachments/assets/21d02c70-f7ff-4c45-a1b4-a582911be412
