### ISSUE TITLE
Nukie Reinforcment does not have ANTAG status

### ISSUE THREAD

**Issue by Keer-Sar** [space-wizards/space-station-14#26710]
## Description

Nukie reinforcements don't have an (ANTAG) status in Admin Alerts or Player Overlay.
**Reproduction**

- Admin Menu (F7 Default Hotkey) > Players > Overlay Toggle
- Use item `syndicate reinforcement radio [NukeOps]`
- Take over new ghost role
- Observe lack up ANTAG in red
- Use any explosive, no (ANTAG) flag in admin alert.
**Screenshots**

![antag lacking](https://github.com/space-wizards/space-station-14/assets/144283718/19fb420f-3611-4fde-ba4a-81df5e72f8bb)
![admin log](https://github.com/space-wizards/space-station-14/assets/144283718/a6391578-c932-4c91-9a6f-6ecd3f8bb01f)

**Additional context**

It should look like this:

![antag slacking](https://github.com/space-wizards/space-station-14/assets/144283718/b121fdb9-b0dd-4889-b05b-3e1aa820573b)
![correct admin log](https://github.com/space-wizards/space-station-14/assets/144283718/15a09806-222a-4288-aa4d-dd2d731cc208)

Aside from log-diving, the reinforcement meme-name is pretty much the only easy dead-giveaway to tell if the reinforcement is actually a reinforcement. The Syndicate Visor correctly puts a big red "S" above the nuke ops reinforcement but not the regular syndicate one.

**Comment by Dutch-VanDerLinde** [comment]
the syndicate icon is supposed to only appear for the nuke-ops reinforcement, not the traitor one

**Comment by 13lackHawk** [comment]
Also no ANTAG status on Rat King and probably every midround antagonist now missing this status.

**Comment by slarticodefast** [comment]
Should be fixed by now thanks to Errant's mind role changes.

**Comment by Errant-4** [comment]
This is not actually fixed, "antag" status is different from the new mind roles. I have been meaning to change the check logic for this use role types, which would update all these issues, but haven't done that yet

**Comment by slarticodefast** [comment]
Oh, nevermind then.

**Comment by Errant-4** [comment]
Also I want to note that the overlay no longer even uses this bool by default, it should show the role type (and soon, an even more specific subtype). Role types are kept more up-to-date, so part of why this issue has been forgotten is that we no longer see it. If anyone has cvar ui.admin_overlay_classic enabled, just turn it off
