### ISSUE TITLE
Pre-mapinit lights don't work so you can't actually see anything

### ISSUE THREAD

**Issue by UbaserB** [space-wizards/space-station-14#27193]
## Description

Makes it harder to map. Visually, the bulbs are gone and when you try to simulate the lighting it only shows tech glow. Turns out it also edits the file itself, but doesn't have an affect on gameplay after mapinit.

**Screenshots**

![image](https://github.com/space-wizards/space-station-14/assets/134914314/8e91aeb3-74f8-49b3-bcab-149b5d2be71f)

![image](https://github.com/space-wizards/space-station-14/assets/134914314/888956bd-31f2-4b6c-a819-f94eae93b19b)

**Comment by ElectroJr** [comment]
Just to clarify, is there actually some bug with mapping mode & mapinitialization, or is this a feature request that lights should be on while mapping?

**Comment by UbaserB** [comment]
> Just to clarify, is there actually some bug with mapping mode & mapinitialization, or is this a feature request that lights should be on while mapping?

I assume it is a bug because this has never happened before

**Comment by ElectroJr** [comment]
NVM I think I misunderstood what you mean. It does seem like theres a bug, I'll work on fixing it tomorrow

**Comment by ElectroJr** [comment]
space-wizards/RobustToolbox/pull/5063 should fix it, though I'll also add a test that the mapping command works as it should to #27207, which we really should've had a long time ago

**Comment by UbaserB** [comment]
It was not fixed

**Comment by UbaserB** [comment]
To clarify, yes his PR _did_ fix adding new light entities, but it did not fix already existing entities from before the change was merged. This means that basically the whole map is still having this problem, and considering the number of lights it would take a million years to fix manually. Ideally, it should be automatic.
