### ISSUE TITLE
Storage Implanter UI Closing Immediately

### ISSUE THREAD

**Issue by Kezu02** [space-wizards/space-station-14#30520]
## Description

Title. After the storage implanter bugs out, trying to open any other inventory does the same.

**Comment by deltanedas** [comment]
fixed by restarting game, incredibly annoying

**Comment by Brandon-Huu** [comment]
Is this related to the implant not opening at all?
I've had this happen to me multiple times and restarting does not fix it.
