### ISSUE TITLE
fatal exception when place pipe

### ISSUE THREAD

**Issue by Ady4ik** [space-wizards/space-station-14#38818]
## Description
The client crashes when you try to build pipes on the Dev map in the designated area

**Reproduction**
We build two pipes as shown in the picture (they must be built):

**Screenshots**
<img width="1919" height="1014" alt="Image" src="https://github.com/user-attachments/assets/4a7c0f31-13d8-4fbf-80fa-58ef50c10aca" />

**Additional context**
https://github.com/SerbiaStrong-220/space-station-14/issues/3137 - main issue

Exception trail:
`Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in .\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Robust.Client.GameObjects.SpriteSystem.GetLocalBounds(Entity`1 sprite) in .\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\SpriteSystem.Bounds.cs:line 24
   at Robust.Client.GameObjects.SpriteSystem.CalculateBounds(Entity`1 sprite, Vector2 worldPos, Angle worldRot, Angle eyeRot) in .\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\SpriteSystem.Bounds.cs:line 127
   at Robust.Client.ComponentTrees.SpriteTreeSystem.ExtractAabb(ComponentTreeEntry`1& entry, Vector2 pos, Angle rot) in .\space-station-14\RobustToolbox\Robust.Client\ComponentTrees\SpriteTreeSystem.cs:line 25
   at Robust.Shared.ComponentTrees.ComponentTreeSystem`2.UpdateTreePositions() in .\space-station-14\RobustToolbox\Robust.Shared\ComponentTrees\ComponentTreeSystem.cs:line 217
   at Robust.Shared.ComponentTrees.ComponentTreeSystem`2.GetIntersectingTrees(MapId mapId, Box2 worldAABB) in .\space-station-14\RobustToolbox\Robust.Shared\ComponentTrees\ComponentTreeSystem.cs:line 274
   at Robust.Shared.ComponentTrees.ComponentTreeSystem`2.GetIntersectingTrees(MapId mapId, Box2Rotated worldBounds) in .\space-station-14\RobustToolbox\Robust.Shared\ComponentTrees\ComponentTreeSystem.cs:line 267
   at Robust.Shared.ComponentTrees.ComponentTreeSystem`2.QueryAabb(MapId mapId, Box2Rotated worldBounds, Boolean approx) in .\space-station-14\RobustToolbox\Robust.Shared\ComponentTrees\ComponentTreeSystem.cs:line 308
   at Robust.Shared.ComponentTrees.ComponentTreeSystem`2.QueryAabb(MapId mapId, Box2 worldBounds, Boolean approx) in .\space-station-14\RobustToolbox\Robust.Shared\ComponentTrees\ComponentTreeSystem.cs:line 303
   at Content.Client.Gameplay.GameplayStateBase.GetClickableEntities(MapCoordinates coordinates, IEye eye, Boolean excludeFaded) in .\space-station-14\Content.Client\Gameplay\GameplayStateBase.cs:line 140
   at Content.Client.Gameplay.GameplayStateBase.GetClickableEntities(MapCoordinates coordinates, Boolean excludeFaded) in .\space-station-14\Content.Client\Gameplay\GameplayStateBase.cs:line 124
   at Content.Client.Sprite.SpriteFadeSystem.FadeIn(Single change) in .\space-station-14\Content.Client\Sprite\SpriteFadeSystem.cs:line 88
   at Content.Client.Sprite.SpriteFadeSystem.FrameUpdate(Single frameTime) in .\space-station-14\Content.Client\Sprite\SpriteFadeSystem.cs:line 174
   at Robust.Shared.GameObjects.EntitySystemManager.FrameUpdate(Single frameTime) in .\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystemManager.cs:line 345
   at Robust.Shared.GameObjects.EntityManager.FrameUpdate(Single frameTime) in .\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityManager.cs:line 302
   at Robust.Client.GameController.Update(FrameEventArgs frameEventArgs) in .\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 619
   at Robust.Client.GameController.<StartupContinue>b__65_3(Object sender, FrameEventArgs args) in .\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.cs:line 272
   at Robust.Shared.Timing.GameLoop.Run() in .\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 290
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in .\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 163
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in .\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 148
   at Robust.Client.GameController.<>c__DisplayClass107_0.<Run>b__0() in .\space-station-14\RobustToolbox\Robust.Client\GameController\GameController.Standalone.cs:line 107`

**Comment by slarticodefast** [comment]
I cannot reproduce this on upstream.
We had this bug a while ago, and I think it was fixed with https://github.com/space-wizards/RobustToolbox/pull/5920
Can you try updating to a newer engine version?

**Comment by CrafterKolyan** [comment]
Agree that it is not reproducible on the latest version of this repo. Sadly we are on the version of engine which contains this fix though still have this exception. Seems to be related to something else

**Comment by Pok27** [comment]
that doesn't happen anymore
