### ISSUE TITLE
Canister slider snaps back to minimum when the UI is opened

### ISSUE THREAD

**Issue by Zumorica** [space-wizards/space-station-14#4267]

**Comment by ElectroJr** [comment]
Can't reproduce. I assume its been fixed at some point.

**Comment by Pangogie** [comment]
> Can't reproduce. I assume its been fixed at some point.

This definitely still happens.
You open the UI, raise the pressure, close it. And when you reopen it the pressure pops back to 0.

**Comment by ElectroJr** [comment]
Oh... I think I was accidentally testing on dirty/modified branch

**Comment by Pangogie** [comment]
![2022-02-10_07-46-45](https://user-images.githubusercontent.com/7548248/153443615-90668232-3b15-4200-b940-8546fea8221c.gif)
