### ISSUE TITLE
Inventory refactor mega-issue

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/space-station-14#5963]
## Description

- [ ] Lights in any inventory slots i.e. helmet lights, pda lights do not show up (https://discord.com/channels/310555209753690112/790656972801572905/926249168131989586)
- [ ] Something is wrong with item action toggling, e.g. magboots (https://discord.com/channels/310555209753690112/790656972801572905/926356595053592596)
- [ ] Character setup screen spamming a zipper sound (https://discord.com/channels/310555209753690112/790656972801572905)/926316047609528321
- [ ] Moony reports inventory being made invisible on her downstream with submod update? (https://discord.com/channels/310555209753690112/790656972801572905/926284098106953869)
- [ ] Can't strip people (https://discord.com/channels/310555209753690112/790656972801572905/926253614534639636)

Comment any more bugs that may be related.

**Comment by Partmedia** [comment]
Locking a locker with "ALT-left click" rapidly locks then unlocks the locker (with corresponding messages on screen). Locking using "right-click, then lock" still work correctly.

Steps to reproduce: attempt to lock an unlocked locker using "ALT-left click".

**Comment by Partmedia** [comment]
Lights fixed by PR #5972 .

**Comment by ZeroDayDaemon** [comment]
Stripping is broken when:
Stunned, Crit, Dead, Handcuffed, or otherwise incapacitated

Fails when the person that's being stripped wouldn't be able to remove that item themselves?

**Comment by ElectroJr** [comment]
Yeah c5a3515 only partially fixed stripping in some situations. #5983 should fix it I think.

**Comment by MeltedPixel** [comment]
Adding, worn item visuals is also currently broken. Example, smoke effects while using joint, cigar, and cigarettes'.

**Comment by PaulRitter** [comment]
should we keep this open? seems inv is pretty much stable now
