### ISSUE TITLE
Connectable entities occasionally begin social distancing.

### ISSUE THREAD

**Issue by Stealthbomber16** [space-wizards/space-station-14#9318]
This is happened three times on live that I know of.

Cables and AME have sometimes decide they are worried about catching the latest COVID variant, and stop attaching to other entities properly, creating some rather cursed scenarios.

![image](https://user-images.githubusercontent.com/100171035/176815834-56426667-1829-4cc3-b8dc-ccc6639e78b7.png)

![image](https://user-images.githubusercontent.com/100171035/176815795-c2e2963e-c941-446b-b74d-4d1aa5633c91.png)

I have also seen this occur with HV cable but I do not have pictures.

**Comment by ElectroJr** [comment]
This is very likely related to the issue causing explosions to break, but at least this side effect should have been fixed by #9309. If this doesn't reoccur after the next publish this can probably be closed.

**Comment by jessicamaybe** [comment]
I just saw this bug happen again, so it's definitely still an issue
![image](https://user-images.githubusercontent.com/31836813/176988823-4c80f4ff-4aa2-4222-9e7d-5d5591254230.png)

**Comment by Stealthbomber16** [comment]
Fixed at some point.
